### ISSUE TITLE
Json compiling errors

### ISSUE THREAD

**Issue by mau-lopez** [lewisxhe/ESP32-Camear-Arduino#1]
Hello lewisxhe, just found your library and look awesome for one of me projects, I'm looking forward to test it! In my first verify, I got the following errors:

Arduino: 1.8.7 (Mac OS X), Board: "ESP32 Dev Module, Disabled, Default, QIO, 80MHz, 4MB (32Mb), 921600, None"

Compiling sketch...
/Users/mau/Library/Arduino15/packages/ArduCAM_ESP32S_UNO/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-g++ -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/config -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/bluedroid -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/bluedroid/api -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/app_trace -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/app_update -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/bootloader_support -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/bt -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/driver -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/esp32 -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/esp_adc_cal -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/esp_http_client -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/esp_https_ota -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/esp-mqtt -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/esp-tls -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/ethernet -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/fatfs -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/freertos -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/heap -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/http_server -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/jsmn -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/log -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/mdns -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/mbedtls -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/mbedtls_port -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/newlib -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/nvs_flash -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/openssl -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/spi_flash -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/sdmmc -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/smartconfig_ack -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/spiffs -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/tcpip_adapter -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/tcp_transport -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/ulp -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/vfs -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/wear_levelling -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/xtensa-debug-module -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/lwip -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/coap -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/console -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/expat -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/json -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/newlib -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/nghttp -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/soc -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/tools/sdk/include/wpa_supplicant -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -MMD -c -DF_CPU=240000000L -DARDUINO=10807 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/cores/esp32 -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/variants/esp32 -I/Users/mau/Developer/Arduino/libraries/ESP32-Camera-Arduino-master/src -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/libraries/WiFi/src -I/Users/mau/Developer/Arduino/hardware/espressif/esp32/libraries/WiFiClientSecure/src -I/Users/mau/Developer/Arduino/libraries/ArduinoJson/src /var/folders/yf/kz_kxlh972n4jdvjn7tcd2cc0000gn/T/arduino_build_150314/sketch/BIGIOT_UpdateImage.ino.cpp -o /var/folders/yf/kz_kxlh972n4jdvjn7tcd2cc0000gn/T/arduino_build_150314/sketch/BIGIOT_UpdateImage.ino.cpp.o
/Users/mau/Developer/Arduino/libraries/ESP32-Camera-Arduino-master/examples/BIGIOT_UpdateImage/BIGIOT_UpdateImage.ino:57:22: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     String request = "POST /pubapi/uploadImg/did/"BIGIOT_DEVICE_ID"/inputid/"BIGIOT_INTERFACE_ID" HTTP/1.1\r\n";

                      ^
/Users/mau/Developer/Arduino/libraries/ESP32-Camera-Arduino-master/examples/BIGIOT_UpdateImage/BIGIOT_UpdateImage.ino:57:67: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     String request = "POST /pubapi/uploadImg/did/"BIGIOT_DEVICE_ID"/inputid/"BIGIOT_INTERFACE_ID" HTTP/1.1\r\n";

                                                                   ^
/Users/mau/Developer/Arduino/libraries/ESP32-Camera-Arduino-master/examples/BIGIOT_UpdateImage/BIGIOT_UpdateImage.ino:20:25: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
                         "Content-Type: image/jpeg\r\n\r\n";

                         ^
/Users/mau/Developer/Arduino/libraries/ESP32-Camera-Arduino-master/examples/BIGIOT_UpdateImage/BIGIOT_UpdateImage.ino:22:21: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *request_end = "\r\n--------------------------ef73a32d43e7f04d--\r\n";

                     ^
BIGIOT_UpdateImage:27:1: error: 'StaticJsonBuffer' does not name a type
 StaticJsonBuffer<512> jsonBuffer;

 ^
/Users/mau/Developer/Arduino/libraries/ESP32-Camera-Arduino-master/examples/BIGIOT_UpdateImage/BIGIOT_UpdateImage.ino: In function 'void update_image()':
BIGIOT_UpdateImage:125:24: error: 'jsonBuffer' was not declared in this scope
     JsonObject &root = jsonBuffer.parseObject(start);

                        ^
BIGIOT_UpdateImage:126:15: error: 'class ArduinoJson660_0_0::JsonObject' has no member named 'success'
     if (!root.success())

               ^
Multiple libraries were found for "WiFi.h"
 Used: /Users/mau/Developer/Arduino/hardware/espressif/esp32/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
Using library ESP32-Camera-Arduino-master at version 0.1.0 in folder: /Users/mau/Developer/Arduino/libraries/ESP32-Camera-Arduino-master 
Using library WiFi at version 1.0 in folder: /Users/mau/Developer/Arduino/hardware/espressif/esp32/libraries/WiFi 
Using library WiFiClientSecure at version 1.0 in folder: /Users/mau/Developer/Arduino/hardware/espressif/esp32/libraries/WiFiClientSecure 
Using library ArduinoJson at version 6.6.0-beta in folder: /Users/mau/Developer/Arduino/libraries/ArduinoJson 
exit status 1
'StaticJsonBuffer' does not name a type

Could you help with this one? Don't know what I am doing wrong. Thanks a lot in advance!

Arduino IDE 1.8.7
MacOS 10.14.1

**Comment by per1234** [comment]
The problem is that the code you're compiling is not compatible with the version of the ArduinoJson library you have installed.

There are two solutions:

- Update the code to work with the 6.x ArduinoJson API: https://arduinojson.org/v6/doc/upgrade/
- Roll back the ArduinoJson library version to the last one with a compatible API: 5.13.2.

Reference: https://arduinojson.org/v5/faq/error-jsonbuffer-was-not-declared-in-this-scope/

**Comment by mau-lopez** [comment]
Thanks you so much for your time and prompt response per1234, indeed that was the problem, I downgraded to Arduinojson 5.13.2 and compiling is ok now! Just another quick question:

How could I change the image size and frame rate? I’m in no way a proficient programmer so I digged a little bit into the files in the src folder and found some lines related with them, I changed nothing there, I just changed line 100 of ESP32_SoftAP_cam to CAMERA_FS_VGA and got an garbage SVGA image in the browser.  With respect to the frame rate, I also have no idea : (

Please let me know if I should close this issue and contact you somehow to solve this question because it is really not an issue? Your help is being much appreciated

Regards!

**Comment by lewisxhe** [comment]
Hi, mau-lopez,the test before changing the image resolution will not work for a while, change the frame rate and although there is an api, but it is not work,because it is not implemented inside， recently too busy, there is no time to perfect this code

**Comment by mau-lopez** [comment]
Lewis, thanks a lot for the information! I will be following your code for any updates, I think it is great to have the camera functionality in Arduino. Thanks again and have a great one!

**Comment by mau-lopez** [comment]
Lewis, thanks a lot for the information! I will be following your code for any updates, I think it is great to have the camera functionality in Arduino. Thanks again and have a great one!

Mauricio López V



On Nov 14, 2018, at 20:11, lewis he <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, mau-lopez, thank you for the answer to per1234，the test before changing the image resolution will not work for a while, change the frame rate and although there is an interface, but it is not perfect, recently too busy, there is no time to perfect this code
